package org.msrg.publiy.broker.core.connectionManager;

public enum ConnectionManagerTypes {

	CONNECTION_MANAGER_JOIN,
	CONNECTION_MANAGER_PUBSUB,
	CONNECTION_MANAGER_RECOVERY,
	
	CONNECTION_MANAGER_MULTIPATH,
	CONNECTION_MANAGER_NC_BROKER,
	CONNECTION_MANAGER_NC_CLIENT,
}
