package org.msrg.publiy.broker.controller.sequence;

public enum SequenceUpdateStatus {

	SEQ_UPDATE_STATUS_NOT_UPDATED,
	SEQ_UPDATE_STATUS_INVALID, 
	
	SEQ_UPDATE_STATUS_CONNECTING,
	SEQ_UPDATE_STATUS_DISCONNECTING,
	SEQ_UPDATE_STATUS_CONNECTED,
	SEQ_UPDATE_STATUS_DISCONNECTED,
	
	SEQ_UPDATE_STATUS_MESSAGE_BEING_SENT,
	SEQ_UPDATE_STATUS_MESSAGE_SENT,
	SEQ_UPDATE_STATUS_MESSAGE_SEND_ERROR;
	
}
