#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing ($0)"
    exit -1; fi
workingdir="$1";

if [ -z "$2" ]; then
    red "No input bandwidth specified ($0)";
    exit -1; fi
inbw="$2";

if [ -z "$3" ]; then
    red "No output bandwidth specified ($0)";
    exit -1; fi
outbw="$3";

for deployfile in `ls $workingdir/deploy-*.sh`; do
    sed -i -e "s/bwIn=.*/bwIn=$inbw/" -e "s/bwOut=.*/bwOut=$outbw/" $deployfile;
done
