#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing!";
    exit -1; fi
workingdir="$1";

if [ -z "$2" ]; then
    red "No column base specified. Use 4 for PUBLICATIONS, 7 for SUBSCRIPTIONS, and 10 for JOINS";
    exit -1; fi
base=$2;

if [ "$base" = "4" ]; then
    yellow "Showing PUBLICATIONS";
elif [ "$base" = "7" ]; then
    yellow "Showing SUBSCRIPTIONS";
elif [ "$base" = "10" ]; then
    yellow "Showing JOINS";
fi

for file in `ls *.confdt`; do
    blue "$file: `awk \"BEGIN{base=$base} {tot[0]+=\\\$(base+0); tot[1]+=\\\$(base+1); tot[2]+=\\\$(base+2);}END{print tot[0],tot[1],tot[2]}\" $file`";
done
