#!/bin/bash

if [ -z "$1" ]; then echo "Missing remote"; exit -1; else remote="$1"; fi;

CL_USER="reza"
CL_HOME="/home/master/$CL_USER";
CL_REPO="$CL_USER/localrepo";
CL_SDIR="$CL_USER/System";

echo "Cleaning remote $remote";
ssh -i ~/.ssh/pl.id_rsa $CL_USER@$remote "rm -fr $CL_SDIR";

