#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working directory is not accessible ($0)";
    exit -1; fi
workingdir="$1";

for resultsdir in `ls -d $workingdir/DT*/`; do
    extract_timing_deliveries $resultsdir;
done

