#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir must be the first arg.";
    exit -1; fi
workingdir=$1;
shift


if [ ! -f "$workingdir/.machinestr" ]; then
    for prop in $workingdir/*.properties; do
        blue $prop;
        node=`awk 'BEGIN{FS="="} /NodeName/{printf $NF}' $prop`;
        machineip=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $2}' $prop`;
        port=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $4}' $prop`;

        machinestr="$machinestr node[\"$port\"]=\"$node\";";
    done
    echo -n "$machinestr" > $workingdir/.machinestr;
else
    yellow "Reusing machine string..."
    machinestr=`cat $workingdir/.machinestr`;
fi

for xtopfile in $* ; do
    blue $xtopfile;
    awk "{RS=\"\\\n|\\\t| \"} /^000/{if(\$1!=time)counter=0; time=\$1} /=========/{counter++;newline=1} /PSSession/{prefix=((newline||1==1)?time\".\"counter\": \":\"          \"); print prefix,gensub(/.*PSSession.*\\[([^\\-]*)-[^_]*_([[:digit:]]*)=>([[:digit:]]*)\\].*/, \"\\\\1 \\\\2 \\\\3\", 1); newline=0;}" $xtopfile | awk "BEGIN{$machinestr} /:/{print \$1, \$2, node[\$3], \$3, node[\$4], \$4} !/:/{print \"         \", \$1, node[\$2], \$2, node[\$3], \$3}" > ${xtopfile}.proc
done
