#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir $1 is not accessible";
    exit -1; fi
workingdir="$1";

for dir in `ls -d $workingdir/DT*`; do
    if [ ! -d "$dir" ]; then
        continue;
    elif [ `expr match "$dir" ".*DELAY.*"` -eq 0 ]; then
        pdelay=`cat $dir/.pdelay`;
        sdelay=`cat $dir/.sdelay`;
        dirname=`echo $dir | awk "{printf subgen(/(.*)-TICK(.*)/,\"\\\\1-DELAY{$pdelay-$sdelay}-TICK\\\\2\", 1)}"`;
        red $dir;
        continue;
        mv $dir $dirname;
    else
        dirname="$dir";
    fi

    pubscount=`count_publishings $dirname`;
    deliveriescount=`count_deliveries $dirname`;
    duplicatescount=`detect_delivered_duplicates $dir | awk '{tot+=$NF}END{printf tot}'`;

    echo "`basename $dirname` => Pub($pubscount), Deliv($deliveriescount), Dup($duplicatescount)";
done > $workingdir/.summaries2
