#!/bin/bash

if [ -z "$1" ]; then
	red "Working directory is missing!";
	exit -1;
fi
workingdir=$1;

PL_USER="utoronto_jacobsen_ft";
PL_HOME="\\/home\\/$PL_USER";

i=0;
for file in `ls $workingdir/s*.properties`; do
	change_filename_dir $PL_HOME\\/System\\/data\\/SubFile_$i.sub $file;
	i=$((++i));
done

i=0;
for file in `ls $workingdir/p*.properties`; do
	change_filename_dir $PL_HOME\\/System\\/data\\/PubFile_$i.pub $file;
	i=$((++i));
done

for file in `ls $workingdir/deploy*.sh`; do
	blue $file;
	change_base_dir $PL_HOME\\/System\\/outputs\\/ $file;
	change_output_dir $PL_HOME\\/System\\/outputs\\/ $file;
done
