#! /bin/awk -f

{tot5+=$5; tot6+=$6; tot8+=$8; tot9+=$9; tot11+=$11; tot12+=$12; tot14+=$14; tot15+=$15; tot16+=$16; tot17+=$17}END{print "P: "tot5"/"tot6"\t S: "tot8"/"tot9"\t J: "tot11"/"tot12"\t C: "tot14"/"tot15"\t A: "tot16"/"tot17;}
