#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir $1 is not accessible ($0)";
    exit -1; fi
workingdir="$1";

summaries_file="$workingdir/.summaries";
if [ -f "$summaries_file" ]; then
    echo "Warning - making summaries again (possibly)!" | tee -a $summaries_file | red; fi

for dir in `ls -d $workingdir/DT*/`; do 
    if [ -d "$dir/temp/" ]; then red "Skipping $dir"; continue; fi
    process $dir/ $summaries_file;
done

make_csv_table2 $workingdir;
