#!/bin/bash

source common.sh

if [ ! -d "$1" ]; then
	red "Working directory is missing!";
	exit -1; fi
workingdir="`cygpath -a $1`";

wait_on_stop "$workingdir/../";

if [ -z "$2" ]; then
    red "No summaries file provided";
else
    summaries_file="$2";
    summaries_file2=$2"2";
fi

CL_ALL_TAR="all.tar.gz";
tempdir="$workingdir/temp";
#tempdir=`mktemp -d`;
if [ ! -d "$tempdir" ]; then
    mkdir -p $tempdir;
    yellow "Processing on `basename $workingdir`";
    (
      for tarfile in `ls $workingdir/*-all.tar.gz`; do
          blue $tarfile;
          tar -C $tempdir -zxf $tarfile;
      done
    )
else
    red "Skipping $tempdir";
fi

process_traffic $workingdir/ $tempdir;
extract_timings_pathlength_deliveries_from_deliv $workingdir $tempdir; 
#add_summaries $workingdir/ $tempdir $summaries_file;
#add_summaries2 $workingdir/ $tempdir $summaries_file2;
process_exec $tempdir;

# rm -rf $tempdir;

