#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing";
    exit -1; fi
workingdir="`cygpath -a $1`";

for dir in `ls -d $workingdir/DT*/`; do
    yellow $dir;
    size_before=`du -h $dir`;
    remove_subw_from_tar $dir;
    size_after=`du -h $dir`;

    green "Size before: $size_before; size after: $size_after";
done

