#!/bin/bash

awk "BEGIN{line=0; firstL=$2+1-1; lastL=$3+1-1; if ( lastL==0 ) lastL=firstL+10; } {line++} {if ( line==firstL ) print firstL,\"---\",lastL,\"==================================================\"; if (line>=firstL && line<=lastL) print \$0}" $1
