package org.msrg.publiy.broker.core.connectionManager.connectionStateMachine;

public enum SessionActionTypes {

	SESSION_A_STATE_TRANSIION,
	SESSION_A_MAKE_OUTGOING,
	SESSION_A_SESSION_ADD,
	SESSION_A_SESSION_REMOVE,
	SESSION_A_RESET_RETRY,
	SESSION_A_DISCONNECT,
	SESSION_A_MQ_ADD,
	SESSION_A_MQ_REMOVE,
	SESSION_A_SET_REAL,
	SESSION_A_UNSET_REAL,
	SESSION_A_UPDATE_CONSIDERATION,
	
}
