package org.msrg.publiy.broker.controller.message;

import java.io.Serializable;

public enum ErrorMessageTypes implements Serializable {

	ERROR_MESSAGE_EXCEPTION_WHILE_EXECUTING_QUERY_MESSAGE,
	ERROR_MESSAGE_EXCEPTION_WHILE_EXECUTING_CONTROL_MESSAGE,
	
	ERROR_MESSAGE_NO_BEROKER_CANNOT_KILL,
	ERROR_MESSAGE_NO_BEROKER_CANNOT_QUERY,
	
	ERROR_MESSAGE_BROKER_EXITS_CANNOT_JOIN,
	ERROR_MESSAGE_BROKER_EXITS_CANNOT_RECOVER,
	
	ERROR_MESSAGE_WRONG_ARG_FORMAT,
	
	ERROR_MESSAGE_UNSUPPORTED_OPERATION,
	ERROR_MESSAGE_OPERATION_FAILED,
}
