package org.msrg.publiy.utils;

public enum HistoryType {

	HIST_T_PUB_OUT_BUTLAST,
	HIST_T_PUB_OUT_WITHLAST,
	HIST_T_PUB_IN_BUTLAST,
	HIST_T_PUB_IN_WITHLAST,
	
	HIST_T_SUB_OUT_BUTLAST,
	HIST_T_SUB_OUT_WITHLAST,
	HIST_T_SUB_IN_BUTLAST,
	HIST_T_SUB_IN_WITHLAST,
	
	HIST_T_JOIN_IN_BUTLAST,
	HIST_T_JOIN_IN_WITHLAST,
	HIST_T_JOIN_OUT_BUTLAST,
	HIST_T_JOIN_OUT_WITHLAST,
	
	HIST_T_CONFS_IN_BUTLAST,
	HIST_T_CONFS_IN_WITHLAST,
	HIST_T_CONFS_OUT_BUTLAST,
	HIST_T_CONFS_OUT_WITHLAST,
	
}
