#!/bin/bash

source common.sh

if [ ! -d "$1" ]; then
    red "Working directory is missing!";
    exit -1; fi
workingdir="`cygpath -a $1`";

wait_on_stop;

red "SKIPPING add_summaries2";
exit 0;

if [ ! -d "$2" ]; then
    red "Temp directory is missing!";
    exit -1; fi
tempdir="$2";

if [ -z "$3" ]; then
    red "No summaries file specified";
    exit -1; fi
summaries_file="$3";

wait_on_stop;

pubscount=`count_publishings $tempdir`;
deliveriescount=`count_deliveries $tempdir`;
duplicatescount=`detect_delivered_duplicates $tempdir | awk '{tot+=$NF}END{printf tot}'`;
subscount=`grep -ai "Adding new sub" $tempdir | wc -l`;

echo "`basename $workingdir` => Pub($pubscount), Deliv($deliveriescount), Dup($duplicatescount), Sub($subscount)" | tee -a $summaries_file | green;
green -e "DONE\n";


