#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing ($0)"
    exit -1; fi
workingdir="$1";

allNodesParamsBegin='Deploy entries for ';
inbwfile="$workingdir/.inbw";
if [ -r "$inbwfile" ]; then
    while read line; do
        green $line;
        poundIndex=`expr match "$line" "[^#]*"`
        line=${line:0:$poundIndex};
        pink $line;
        array=($line);
        arraylen=${#array[*]};
        value="${array[0]}";
        if [ ${#array[*]} -eq 0 ]; then
            continue;
        elif [ ${#array[*]} -eq 1 ]; then
            inbw=${array[0]};
            sed -i -e "/.*bwIn=.*/d" $workingdir/deploy-*.sh;
            sed -i -e "s/\(.*Deploy entries for ALL nodes.*\)/\\1\nbwIn=$inbw/"  $workingdir/deploy-*.sh;
            continue;
        fi

        i=0;
        while [ $((++i)) -lt $arraylen ]; do
            node="${array[$i]}";
            address=`awk 'BEGIN{FS="\\\\\\\\|="}/NodeAddress/{print $2}' $workingdir/$node.properties`;
            deployfile="deploy-$address.sh";
            blue "INBW: $node ($address) -> $value";

        params="bwIn=$value"
        change_node_specific_param $deployfile $node $params;
        done
    done < $inbwfile;
fi;

outbwfile="$workingdir/.outbw";
if [ -r "$outbwfile" ]; then
    while read line; do
        green $line;
        array=($line);
        arraylen=${#array[*]};
        value="${array[0]}";
        if [ ${#array[*]} -eq 1 ]; then
            outbw=${array[0]};
            sed -i -e "/.*bwOut=.*/d" $workingdir/deploy-*.sh;
            sed -i -e "s/\(.*Deploy entries for ALL nodes.*\)/\\1\nbwOut=$outbw/"  $workingdir/deploy-*.sh;
            continue;
        fi

i=0;
        while [ $((++i)) -lt $arraylen ]; do
            node="${array[$i]}";
            address=`awk 'BEGIN{FS="\\\\\\\\|="}/NodeAddress/{print $2}' $workingdir/$node.properties`;
            deployfile="deploy-$address.sh";
            blue "OUTBW: $node ($address) -> $value";

        params="bwOut=$value"
        change_node_specific_param $deployfile $node $params;
        done    done < $outbwfile;
fi;
