#!/bin/bash

if [ ! -d "$1" ]; then
    red "Invalid working dir $1";
    exit -1; fi
workingdir="$1";

pdelay=50;
sdelay=100;
BW_METRIC=BW_METRIC_INOUT_BYTES;
BW_METRIC=BW_METRIC_UNLIMITTED;
BW_VALUE="*";
BW_VALUE=10000;
BW_VALUE=30000;
BW_VALUE=300000;
#BW_VALUE=100000000;
workload=1000

all_filenames=""
for mult in 1 10; do
for fanout in 10 15 20; do
    for delta in 1 2 3; do
        throughput_filename="$workingdir/plots/mult${mult}_delay${pdelay}_${BW_METRIC}_delta${delta}_fanout${fanout}.throughputs"
        green $throughput_filename;
        echo "" > $throughput_filename;
        all_filenames="$throughput_filename $all_filenames"

        for str in 1 2 3; do
            publishings="";
            deliveries="";
            execno="";
            yellow "Delta: $delta, Fanout: $fanout, Strategy: $str";
            for DT in `ls -d $workingdir/DT*MULT$mult.*DELAY{$pdelay-$sdelay}*-d$delta-sSTR$str-W$workload-*FOUT$fanout*$BW_METRIC*${BW_VALUE}}__*`; do
                blue $DT;
                execno=${DT:`expr match "$DT" ".*__."`};
                execnos="$execno $execnos"
                countall="`awk '/==>/{print $2,$3;}' $DT/.countall`";
                publishing=${countall:0:`expr match "$countall" "[^ ]*"`};
                delivery=${countall:`expr match "$countall" "[^ ]* "`};
                deliveries="$delivery $deliveries";
                publishings="$publishing $publishings";
            done;
            red "$str $deliveries";
            echo "  $str $deliveries" >> $throughput_filename;
            echo "# $str $publishings" >> $throughput_filename;
            echo "##$str $execnos" >> $throughput_filename;
        done;
    done;
done;
done;

for throwput_file in $all_filenames; do # `ls $workingdir/plots/*.throughputs`; do
     blue $throwput_file;
     awk '!/#/&&/[[:digit:]]+/{max1=0;max2=0;max3=0; for(i=2;i<=NF;i++){if($i>max1){max3=max2;max2=max1;max1=$i;} else if ($i>max2) {max3=max2;max2=$i;} else if ($i>max3){max3=$i} } print $1,max1,max2,max3; print "#"$0}' $throwput_file > ${throwput_file}.proc;
done
