#!/bin/bash

source common.sh

if [ -z "$1" ]; then
    red "Missing working dir ($0)";
    exit -1; fi
workingdir="$1";

process1() {
    local resultsdir="$1";
    local tempdir="$2";
    local plotsdir="$3";
    blue "Process 1 on $resultsdir";
    all_ports="";
    all_machines="";
    all_subs="";
    all_pubs="";

    # Process publishers
    for pubprop in $resultsdir/p*.properties; do
        node=`awk 'BEGIN{FS="="} /NodeName/{printf $NF}' $pubprop`;
        machineip=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $2}' $pubprop`;
        port=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $4}' $pubprop`;

        portstr="$portstr port[$port]=\"$node\";";
        nodestr="$nodestr node[\"$node\"]=\"$machineip\";";

        all_machines="$machine $all_machines";
        all_ports="$port $all_ports";
        all_pubs="$node $all_pubs";
    done

    # Process subscribers
    for subprop in $resultsdir/s*.properties; do
        node=`awk 'BEGIN{FS="="} /NodeName/{printf $NF}' $subprop`;
        machineip=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $2}' $subprop`;
        port=`awk 'BEGIN{FS="\\\\\\\\|:|="} /NodeAddress/ {printf $4}' $subprop`;

        portstr="$portstr port[$port]=\"$node\";";
        nodestr="$nodestr node[\"$node\"]=\"$machineip\";";

        all_machines="$machine $all_machines";
        all_ports="$port $all_ports";
        all_subs="$node $all_subs";
    done

    for sub in $all_subs; do
        subresultsfile="$tempdir/BC-$sub*";
        awk "/DELIV/{print gensub(/.*@([[:digit:]]*).*TMulticast_Publication_MP\[ [^ ]* [^ ]* (.*)\] ([[:digit:]]*) [^ ]* Seq.*/,\"\\\\1 \\\\2 \\\\3\",1)}" $subresultsfile | awk "BEGIN{$portstr $nodestr} {print \$1\"\t$sub\",node[\"$sub\"],\$3\"\t\"port[\$5],node[port[\$5]],\$4,\$2}";
    done > $plotsdir/delivery_pathlength_timings;
}

function process2() {
    local resultsdir="$1";
    local tempdir="$2";
    local plotsdir="$3";
    if [ ! -d "$plotsdir" ]; then
        mkdir $plotsdir; fi
    blue "Process 2 on $resultsdir";
    
    awk 'func abs(val){if(val<=0)return -val; else return val}
         BEGIN{l=0;} {
            i=$3"_"$6;
            if(count[i]==0)
                pair[++l]=i;
            count[i]++;
            timing[i]=timing[i]"\t"($1)" "($4-$7)" "($8);
    } END{
            l=asorti(timing, sorted_indices);
            for(j=1;j<=l;j++){
                i=sorted_indices[j];
                print i"\t"timing[i];
            }
    }' $plotsdir/delivery_pathlength_timings > $plotsdir/delivery_pathlength_timings_grouped;
}

function process3() {
    local resultsdir="$1";
    local tempdir="$2";
    local plotsdir="$3";
    if [ ! -d "$plotsdir" ]; then
        mkdir $plotsdir; fi
    blue "Process 3 on $resultsdir";
    awk 'BEGIN{print "#Peer2Peer\tTotalTime\tTotalPathLen\tTotalDel\tAvgTime\tAvgPathLen"} {tot=0;totpath=0;for(i=2;i<=NF;i+=3){tot+=$(1+i); totpath+=$(i+2);} print $1"\t"tot"\t"totpath"\t"((NF-1)/3)"\t"(NF<=1?"--":(tot/((NF-1)/3)))"\t"(NF<=1?"--":(totpath/((NF-1)/3)))}' $plotsdir/delivery_pathlength_timings_grouped > $plotsdir/delivery_pathlength_timings_summary;
}

function process4() {
    local resultsdir="$1";
    local tempdir="$2";
    local plotsdir="$3";
    blue "Process 4";
    awk '{tot_time+=$2; tot_path_len+=$3; tot_msg+=$4;}END{print "TotalTime\tTotalPathLen\tTotalDel\tAvgTime\tAvgPathLen"; print tot_time"\t"tot_path_len"\t"(tot_msg)"\t"(tot_time/tot_msg)"\t"(tot_path_len/tot_msg)}' $plotsdir/delivery_pathlength_timings_summary > $plotsdir/delivery_pathlength_timings_final_summary;
}

function process5() {
    local resultsdir="$1";
    local tempdir="$2";
    local plotsdir="$3";
    local p2psdir="$plotsdir/p2p";
    mkdir $p2psdir;
    blue "Process 5";
    p2p_all=`awk '{printf $1" "}' $plotsdir/delivery_pathlength_timings_grouped`;
    for p2p in $p2p_all; do
        awk "/$p2p/{for(i=2;i<=NF;i+=3) {print \$i\"\t\"\$(i+1)\"\t\"\$(i+2)}}"  $plotsdir/delivery_pathlength_timings_grouped > $p2psdir/$p2p;
    done
}
 
if [ ! -d "$1" ]; then
    red "Results dir is not accessible";
    exit -1; fi
resultsdir="$1";
if [ -d "$2" ]; then
    tempdir="$2";
    shift;
else
    tempdir="$resultsdir/temp";
    if [ ! -d "$tempdir" ]; then
        red "No temp dir under results dir";
        exit -1; fi
fi

plotsdir="$resultsdir/plots";
if [ ! -d "$plotsdir" ]; then
    mkdir -p $plotsdir;
else
    red "Skipping $resultsdir"; fi
yellow "`basename $resultsdir`";
    wait_on_stop;

shift;
if [ -z "$1" ]; then
    process1 $resultsdir $tempdir $plotsdir;
    wait_on_stop;
    process2 $resultsdir $tempdir $plotsdir;
    wait_on_stop;
    process3 $resultsdir $tempdir $plotsdir;
    wait_on_stop;
    process4 $resultsdir $tempdir $plotsdir;
    wait_on_stop;
    # process5 $resultsdir $tempdir $plotsdir;
    green "DONE. `wc -l $plotsdir/delivery_pathlength_timings | awk '{printf $1}'`";
    exit 0;
fi


while [ ! -z "$1" ]; do
    if [ "$1" = "P1" ]; then
        process1 $resultsdir $tempdir $plotsdir;
    elif [ "$1" = "P2" ]; then
        process2 $resultsdir $tempdir $plotsdir;
    elif [ "$1" = "P3" ]; then
        process3 $resultsdir $tempdir $plotsdir;
    elif [ "$1" = "P4" ]; then
        process4 $resultsdir $tempdir $plotsdir;
    elif [ "$1" = "P5" ]; then
        process5 $resultsdir $tempdir $plotsdir;
    fi
    shift;
done


