#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing ($0)";
    exit -1; fi
workingdir="$1";

names="";
for prop in `ls $workingdir/s*.properties`; do
    name=`awk 'BEGIN{FS="="}/NodeName/{printf $NF}' $prop`;
    names="$name $names";
done

echo $names;
