#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir $1 is not accessible";
    exit -1; fi
workingdir="$1";

outputfile="$workingdir/`basename $workingdir`_pathlength_table.csv";

echo "#MULT, PDELAY, SDELAY, TICK, STR, DELIV, TOTLEN, AVGLEN, EXECNO, COMMENT" > $outputfile;

for resultsdir in `ls -d $workingdir/DT*`; do
    plotsdir=$resultsdir/plots;

    if [ ! -r "$resultsdir/.pdelay" ]; then
        pdelay="`echo $resultsdir | awk '{printf gensub(/.*DELAY{([[:digit:]]*)\-([[:digit:]]*)}.*/,\"\\\\1\",1)}'`";
    else 
        pdelay=`cat $resultsdir/.pdelay`; fi

    if [ ! -r "$resultsdir/.sdelay" ]; then
        sdelay="`echo $resultsdir | awk '{printf gensub(/.*DELAY{([[:digit:]]*)\-([[:digit:]]*)}.*/,\"\\\\2\",1)}'`";
    else
        sdelay=`cat $resultsdir/.sdelay`; fi

     if [ ! -r "$resultsdir/.strategy" ]; then
        strategy="`echo $resultsdir | awk '{printf gensub(/.*STR([[:digit:]]*).*/,\"\\\\1\",1)}'`";
    else 
        strategy=`cat $resultsdir/.strategy`; fi

    if [ ! -r "$resultsdir/.tickscaler" ]; then
        tick="-1";
    else
        tick=`cat $resultsdir/.tickscaler`; fi

    mult="`echo $resultsdir | awk '{printf gensub(/.*MULT([[:digit:]]*)\..*/, \"\\\\1\", 1)}'`";
    execno="`echo $resultsdir | awk '{printf gensub(/.*__([[:digit:]]*).*/, \"\\\\1\", 1)}'`";

    final_summmary_str="";
    final_summary="`cat $plotsdir/delivery_pathlengths_final_summary`";
    for i in $final_summary; do final_summmary_str="$final_summmary_str,\t$i"; done
    echo -e "$mult,\t$pdelay,\t$sdelay,\t$tick,\t$strategy$final_summmary_str,\t$execno,\t$resultsdir";
done  >> $outputfile;

