#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir is missing.";
    exit -1; fi
workingdir="$1";
backupdir="$workingdir/backup_ready";

if [ ! -d "$backupdir" ]; then
    red "Backup dir $backupdir is missing.";
    exit -1; fi

for d in 1 2 3; do
    for fout in 10 15; do
        dir=$workingdir/backup_ready_delta${d}_fanout${fout}/;
        rm -r $dir;
        blue $dir;
        cp -r $backupdir/ $dir;
        sed -i -e "s/delta=.*/delta=$d/" -e "s/fanout=.*/fanout=$fout/" $dir/deploy*;
    done;
done
