#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working directory is missing!";
    exit -1; fi
workingdir="`cygpath -a $1`";

if [ ! -d "$2" ]; then
    red "Temp directory is missing!";
    exit -1; fi
tempdir="$2";

plotdir="$workingdir/plots/"
if [ ! -d "$plotdir" ]; then
    mkdir -p $plotdir; fi

# Clean traffic files
CLEAN_TRAFFIC_COL_COUNT=35;
clean_traffic $CLEAN_TRAFFIC_COL_COUNT $tempdir/*.traffic;

# Sum up columns across all cleaned traffic files;
sumup_cols_across_files $tempdir/*.traffic.clean$CLEAN_TRAFFIC_COL_COUNT > $plotdir/summedup_traffic;

generate_send_receved_dataset $tempdir/ > $plotdir/send_received_dataset;
avg $plotdir/send_received_dataset | awk '{print $3, $4}' > $plotdir/avg_send_received;

for window in 1 2 3 5 10; do
    avgwindowfile=$plotdir/summedup_$window"avgwindow_traffic";	
    avg_window $window $plotdir/summedup_traffic>$avgwindowfile;
done


