#!/bin/bash

if [ ! -d "$1" ]; then
    red "Working dir $1 is not accessible ($0)";
    exit -1; fi
workingdir="$1";

for dir in `cat $workingdir/.process.todo`; do 
    dir="$workingdir/$dir";
    process $dir/ $summaries_file;
done


