#!/bin/bash

source common.sh

if [ ! -d "$1" ]; then
    red "Working dir is missing!";
    exit -1; fi
workingdir="`cygpath -a $1`";

wait_on_stop;

for exec in `ls $workingdir/*.exec`; do 
    blue -en "`basename $exec` ";
    awk '/TIME/{print} !/TIME/{printf $1; for (i=1; i<=(NF/2); i++) printf "\t"($(i*2+1)==0?0:($(i*2)/$(i*2+1))); print "";}' $exec > $exec.proc;
done
