#!/bin/bash

awk "
	{
	  if(NF>max_col_count)
	    max_col_count = NF;
	  for(i=1;i<=NF;i++) {
		tot[i] += \$i;
	  }
	}
	END{
	  for(i=1;i<=max_col_count;i++)
		printf tot[i]\" \";
	  print \"\";
	}
" $1;
