package org.msrg.publiy.component;

public enum ComponentStatus {
	
	COMPONENT_STATUS_UNINITIALIZED,
	COMPONENT_STATUS_INITIALIZING,
	COMPONENT_STATUS_INITIALIZED,
	
	COMPONENT_STATUS_STARTING,
	COMPONENT_STATUS_RUNNING,
	
	COMPONENT_STATUS_PAUSING,
	COMPONENT_STATUS_PAUSED,
	
	COMPONENT_STATUS_STOPPING,
	COMPONENT_STATUS_STOPPED,
	
	COMPONENT_STATUS_PROBLEM

}
